name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        build_type: [debug, release]
    container: victorbaldin56/bitonic_sort:918b8e65d0fd8fcff3ea167d76df835cb89bcb55

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Conan install
      run: |
        conan install .
          -pr=ci/profiles/${{ matrix.compiler }}_${{ matrix.build_type }}.profile
          --output-folder=build
          --build=missing

    - name: Configure
      run: cmake . -B build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build -j

    - name: Run tests
      run: cd build && ctest --output-on-failure
