name: CMake with multiple configs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]
    container: victorbaldin56/bitonic_sort:62b2637c72aed0feaa2d6ce110d4b240de9208a1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Conan install
      run: |
        conan profile detect --force &&
        conan install . \
          -pr=ci/profiles/${{ matrix.build_type }}.profile \
          --output-folder=build \
          --build=missing

    - name: Configure
      run: cmake . -B build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build -j

    - name: Run tests
      run: cd build && ctest --output-on-failure
